ALTER TABLE "rpgs"
ADD COLUMN IF NOT EXISTS "costs_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "cost_resource_name" TEXT NOT NULL DEFAULT 'Skill Points';

ALTER TABLE "rpg_characters"
ADD COLUMN IF NOT EXISTS "skill_points" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "abilities" JSONB NOT NULL DEFAULT '[]'::jsonb;
