FROM node:22-alpine

WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm ci

COPY . ./

RUN npm run prisma:generate

EXPOSE 4000

CMD ["npm", "run", "start"]
